### PR TITLE
KDE KF6 update

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by travier** [comment]
This wants:

```
CMake Error at src/CMakeLists.txt:53 (target_link_libraries):
  Target "arianna_static" links to:
    Qt6::HttpServer
```

Maybe this should be included in the Runtime?

**Comment by tsdgeos** [comment]
Arianna is the only software that uses qt6-httpserver, so maybe just include it here for now?

Curiosity: Can a flatpak even open a local http server?

**Comment by travier** [comment]
```
QIBusPlatformInputContext: invalid portal bus.
"Running on http://127.0.0.1:45961/ (Press CTRL+C to quit)"
qt.qml.typeresolution.cycle: Cyclic dependency detected between "qrc:/qt/qml/org/kde/desktop/private/TextFieldContextMenu.qml" and "qrc:/qt/qml/org/kde/desktop/MenuItem.qml"
QQmlApplicationEngine failed to load component
qrc:/content/ui/main.qml:32:22: Type LibraryPage unavailable
qrc:/content/ui/LibraryPage.qml:6:1: module "QtWebEngine" plugin "qtwebenginequickplugin" not found
```

**Comment by tsdgeos** [comment]
Interesting seems like if the webeninge thing is not building the QML plugin, do you know where that is built?

**Comment by travier** [comment]
This one works for me but it stays opened after I close the main window and we don't have a status icon. Not sure if that's expected or if we're missing something.

**Comment by travier** [comment]
Any idea @CarlSchwan ?

**Comment by travier** [comment]
I'm going to merge this as I see the same behavior with the current version.

**Pull request merged**
